FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3

#ADD https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz /usr/local
#RUN microdnf install -y xz tar && \
#    xz -d -c /usr/local/upx-3.96-amd64_linux.tar.xz | tar -xOf - upx-3.96-amd64_linux/upx > /bin/upx && \
#    chmod a+x /bin/upx
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root standortkarte-server/target/ch.so.agi.standortkarte.application /work/application

EXPOSE 8080
USER 1001

#Log4j 2 CVE-2021-44228
ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true

CMD ["./application"]
